version: '3.3'

volumes:
  static_value:
  db_data:
  redoc:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    ports:
      - "80:8000"
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

