name: Places_Remember_workflow
on: [push]
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  YANDEX_MAPS_API_KEY: ${{ secrets.YANDEX_MAPS_API_KEY }}
  SOCIAL_AUTH_VK_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_KEY }}
  SOCIAL_AUTH_VK_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_SECRET }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.12
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./requirements.txt
            python ./places_remember_project/manage.py makemigrations
            python ./places_remember_project/manage.py migrate
        - name: Test with flake8
          run: flake8 .
        - name: General tests
          run: pytest ./places_remember_project/


        
